# Win Rate Optimized Configuration
# Generated for boosting win rate from 53.4% to 60%+
# Focus: Quality over quantity

# Core settings
seed: 42

# Optimization goals - QUALITY FOCUSED
goals:
  win_rate_range: [0.60, 0.75]      # Increased from [0.55, 0.75]
  risk_reward_range: [2.2, 4.0]     # Increased from [1.6, 3.5]
  trades_per_week_range: [25, 35]   # Reduced from [30, 60] - quality focus

# Data configuration
data:
  input_dir: "data/raw/"
  prepared_file: "data/prepared.csv"
  labeled_file: "data/labeled.csv"
  models_dir: "models/"
  data_dir: data
  log_dir: logs

# Market settings
market:
  timezone: "America/Chicago"
  weekly_open: "Sunday 16:00"
  weekly_close: "Friday 16:00"

# Walk-forward parameters
walkforward:
  stepback_weeks: 12
  train_window_months: 18
  validation_window_months: 3
  min_trades_per_week: 8
  max_trades_per_week: 120
  window_weeks: 1

# Data preparation
prepare:
  lookback_years: 5
  n_clusters: 3
  lag_periods: [1, 3, 5, 10]
  indicators:
    ema: [5, 20]
    rsi: [7, 14]
    ichimoku: [9, 26, 52]
    adx: 14
    atr: 14
    bollinger: 20
    stochastic: [14, 3]

# ULTRA-STRICT LABELING for quality
label:
  future_window: 24
  threshold: 0.0012              # Increased from 0.0008 (1.2 pips vs 0.8 pips)
  max_sl_pips: 20                # Reduced from 22 (tighter stops)
  min_rr: 2.2                    # Increased from 1.8 (higher RR requirement)
  take_profit: 15
  max_stop_loss: 15
  max_bars: 48
  cooldown_min: 10               # Increased from 5 (avoid clustering)
  min_rr_target: 2.2             # Increased from 2.0
  min_win_rate_target: 0.65      # Increased from 0.55 (strict target)
  enhanced_quality_scoring: true

# QUALITY-FOCUSED SIGNAL PARAMETERS
signal:
  min_confidence_threshold: 0.65  # Increased from 0.6
  min_precision_target: 0.80     # Increased from 0.75
  min_signals_per_week: 8        # Reduced from 12 (quality over quantity)
  sequence_length: 32
  batch_size: 256
  epochs: 10
  patience: 2
  positive_cap: 50000
  negative_cap: 80000
  model:
    lstm_units: 64
    dropout: 0.2
  precision_filter:
    thresholds: [0.6, 0.7, 0.75, 0.8]  # Increased from [0.45, 0.55, 0.6, 0.65]
    base_features:
      - return_1
      - atr
      - rsi_14
      - stochastic_k
      - hour
      - weekday
      - session_london
      - session_ny
  multi_timeframe_features: true
  enhanced_meta_model: true
  features:
    # Price and volume features
    - open
    - high
    - low
    - close
    - volume
    
    # Technical indicators with lag
    - ema_5
    - ema_5_lag_1
    - ema_5_lag_3
    - ema_5_lag_5
    - ema_5_lag_10
    - ema_10
    - ema_10_lag_1
    - ema_10_lag_3
    - ema_10_lag_5
    - ema_10_lag_10
    - ema_20
    - ema_20_lag_1
    - ema_20_lag_3
    - ema_20_lag_5
    - ema_20_lag_10
    - ema_50
    - ema_50_lag_1
    - ema_50_lag_3
    - ema_50_lag_5
    - ema_50_lag_10
    - rsi_14
    - rsi_14_lag_1
    - rsi_14_lag_3
    - rsi_14_lag_5
    - rsi_14_lag_10
    - rsi_28
    - rsi_28_lag_1
    - rsi_28_lag_3
    - rsi_28_lag_5
    - rsi_28_lag_10
    - macd
    - macd_signal
    - macd_diff
    - ichimoku_tenkan
    - ichimoku_kijun
    - ichimoku_senkouA
    - ichimoku_senkouB
    - ichimoku_chikou
    - adx
    - plus_di
    - minus_di
    - atr
    - atr_pct
    - bb_upper
    - bb_middle
    - bb_lower
    - bb_width
    - stochastic_k
    - stochastic_d
    - cmf
    - mfi
    - bar_volatility
    - relative_tick_volume
    - return_1
    - return_3
    - return_5
    - return_10
    
    # Time-based features
    - hour
    - weekday
    - session_asian
    - session_london
    - session_ny
    - session_overlap
    
    # Market regime
    - market_regime

# SL/TP parameters - OPTIMIZED FOR QUALITY
sltp:
  min_tp: 3                      # Reduced from 4 (more granular)
  max_tp: 30                     # Increased from 28
  tp_step: 1                     # Reduced from 2 (more options)
  min_rr: 2.2                    # Increased from 2.0 (higher quality)
  features:
    - close
    - high
    - low
    - volume
    - ema_5
    - ema_10
    - ema_20
    - ema_50
    - rsi_14
    - rsi_28
    - macd
    - macd_signal
    - macd_diff
    - ichimoku_tenkan
    - ichimoku_kijun
    - ichimoku_senkouA
    - ichimoku_senkouB
    - ichimoku_chikou
    - adx
    - plus_di
    - minus_di
    - atr
    - atr_pct
    - bb_upper
    - bb_middle
    - bb_lower
    - bb_width
    - stochastic_k
    - stochastic_d
    - cmf
    - mfi
    - bar_volatility
    - relative_tick_volume
    - return_1
    - return_3
    - return_5
    - return_10
    - hour
    - weekday
    - session_asian
    - session_london
    - session_ny
    - session_overlap

# SL/TP grid - EXPANDED FOR QUALITY
sl_tp_grid:
  spread: 0.00013
  sl_multipliers: [2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0, 5.2, 5.4, 5.6, 5.8, 6.0, 6.2, 6.4, 6.6, 6.8, 7.0, 7.2, 7.4, 7.6, 7.8, 8.0]
  tp_multipliers: [2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0]  # Higher minimum RR

# CONSERVATIVE SIMULATION PARAMETERS
simulation:
  initial_balance: 10000
  position_size: 0.1
  max_positions: 1               # SINGLE POSITION for quality focus
  risk_per_trade: 0.015          # Reduced from 0.02 (conservative)
  cooldown_min: 15               # Increased from 5 (avoid clustering)
  max_daily_trades: 6            # Reduced from 8 (selective)
  max_weekly_trades: 35          # Reduced from 50 (quality focus)
  max_drawdown: 0.12             # Reduced from 0.15 (tighter control)
  stop_trading_drawdown: 0.08    # Reduced from 0.10 (early stop)
  advanced_risk_management: true
  dynamic_sizing: true
  session_filters:
    asian: false                 # DISABLED (lower quality)
    london: true                 # Premium session
    ny: true                     # Good session
    overlap: true                # Best session (London/NY)
  market_regime_filters:
    - 0                          # Best regime only
    - 1                          # Good regime only
    # Regimes 2+ disabled (high volatility)

# QUALITY-FOCUSED RANKER
ranker:
  target_trades_per_week: 30     # Reduced from 40 (quality focus)
  min_trades_per_week: 20        # Reduced from 25
  max_trades_per_week: 40        # Reduced from 50
  quality_threshold: 0.8         # Increased from 0.7 (stricter)
  enhanced_filtering: true
  confidence_based_sizing: true

# STRICT ACCEPTANCE CRITERIA
acceptance:
  prepare:
    min_rows: 50000
    max_nan_percent: 2
  train:
    min_precision: 0.0
  sltp:
    min_rr: 2.2                  # Increased from 2.0
  simulation:
    min_win_rate: 0.60           # Increased from 0.58 (TARGET)
    min_profit_factor: 1.8       # Increased from 1.5
    max_drawdown: 0.12           # Reduced from 0.15
    min_trades_per_week: 20      # Reduced from 25 (quality focus)

# Backtesting parameters
backtest:
  risk_pct: 2.5
  min_profit_factor: 1.8         # Increased from 1.0
  max_drawdown: 0.10             # Reduced from 0.15
  min_avg_rr: 2.2               # Increased from 2.0