acceptance:
  prepare:
    max_nan_percent: 2
    min_rows: 50000
  simulation:
    max_drawdown: 0.15
    min_profit_factor: 1.5
    min_trades_per_week: 20
    min_win_rate: 0.58
  sltp:
    min_rr: 2.0
  train:
    min_precision: 0.0
backtest:
  max_drawdown: 0.1
  min_avg_rr: 2.0
  min_profit_factor: 1.0
  risk_pct: 2.5
data:
  data_dir: data
  input_dir: data/raw/
  labeled_file: data/labeled.csv
  log_dir: logs
  models_dir: models/
  prepared_file: data/prepared.csv
goals:
  risk_reward_range:
  - 1.6
  - 3.5
  trades_per_week_range:
  - 25
  - 50
  win_rate_range:
  - 0.55
  - 0.75
label:
  cooldown_min: 5
  future_window: 24
  max_bars: 48
  max_sl_pips: 22
  max_stop_loss: 15
  min_rr: 1.8
  min_rr_target: 2.0
  min_win_rate_target: 0.55
  take_profit: 15
  threshold: 0.0008
market:
  timezone: America/Chicago
  weekly_close: Friday 16:00
  weekly_open: Sunday 16:00
prepare:
  indicators:
    adx: 14
    atr: 14
    bollinger: 20
    ema:
    - 5
    - 20
    ichimoku:
    - 9
    - 26
    - 52
    rsi:
    - 7
    - 14
    stochastic:
    - 14
    - 3
  lag_periods:
  - 1
  - 3
  - 5
  - 10
  lookback_years: 5
  n_clusters: 3
ranker:
  max_trades_per_week: 50
  min_trades_per_week: 20
  target_trades_per_week: 35
seed: 42
signal:
  batch_size: 256
  epochs: 10
  features:
  - open
  - high
  - low
  - close
  - volume
  - ema_5
  - ema_5_lag_1
  - ema_5_lag_3
  - ema_5_lag_5
  - ema_5_lag_10
  - ema_10
  - ema_10_lag_1
  - ema_10_lag_3
  - ema_10_lag_5
  - ema_10_lag_10
  - ema_20
  - ema_20_lag_1
  - ema_20_lag_3
  - ema_20_lag_5
  - ema_20_lag_10
  - ema_50
  - ema_50_lag_1
  - ema_50_lag_3
  - ema_50_lag_5
  - ema_50_lag_10
  - rsi_14
  - rsi_14_lag_1
  - rsi_14_lag_3
  - rsi_14_lag_5
  - rsi_14_lag_10
  - rsi_28
  - rsi_28_lag_1
  - rsi_28_lag_3
  - rsi_28_lag_5
  - rsi_28_lag_10
  - macd
  - macd_signal
  - macd_diff
  - ichimoku_tenkan
  - ichimoku_kijun
  - ichimoku_senkouA
  - ichimoku_senkouB
  - ichimoku_chikou
  - adx
  - plus_di
  - minus_di
  - atr
  - atr_pct
  - bb_upper
  - bb_middle
  - bb_lower
  - bb_width
  - stochastic_k
  - stochastic_d
  - cmf
  - mfi
  - bar_volatility
  - relative_tick_volume
  - return_1
  - return_3
  - return_5
  - return_10
  - hour
  - weekday
  - session_asian
  - session_london
  - session_ny
  - session_overlap
  - market_regime
  min_precision_target: 0.75
  min_signals_per_week: 12
  model:
    dropout: 0.2
    lstm_units: 64
  negative_cap: 80000
  patience: 2
  positive_cap: 50000
  precision_filter:
    base_features:
    - return_1
    - atr
    - rsi_14
    - stochastic_k
    - hour
    - weekday
    - session_london
    - session_ny
    thresholds:
    - 0.5
    - 0.6
    - 0.65
    - 0.7
  sequence_length: 32
simulation:
  cooldown_min: 5
  initial_balance: 10000
  market_regime_filters:
  - 0
  - 1
  - 2
  - 3
  max_daily_trades: 8
  max_drawdown: 0.15
  max_positions: 2
  max_weekly_trades: 40
  position_size: 0.1
  risk_per_trade: 0.02
  session_filters:
    asian: true
    london: true
    ny: true
    overlap: true
  stop_trading_drawdown: 0.1
sl_tp_grid:
  sl_multipliers:
  - 2.4
  - 2.6
  - 2.8
  - 3.0
  - 3.2
  - 3.4
  - 3.6
  - 3.8
  - 4.0
  - 4.2
  - 4.4
  - 4.6
  - 4.8
  - 5.0
  - 5.2
  - 5.4
  - 5.6
  - 5.8
  - 6.0
  - 6.2
  - 6.4
  - 6.6
  - 6.8
  - 7.0
  - 7.2
  - 7.4
  - 7.6
  - 7.8
  - 8.0
  spread: 0.00013
  tp_multipliers:
  - 1.8
  - 2.0
  - 2.2
  - 2.4
  - 2.6
  - 2.8
  - 3.0
  - 3.2
sltp:
  features:
  - close
  - high
  - low
  - volume
  - ema_5
  - ema_10
  - ema_20
  - ema_50
  - rsi_14
  - rsi_28
  - macd
  - macd_signal
  - macd_diff
  - ichimoku_tenkan
  - ichimoku_kijun
  - ichimoku_senkouA
  - ichimoku_senkouB
  - ichimoku_chikou
  - adx
  - plus_di
  - minus_di
  - atr
  - atr_pct
  - bb_upper
  - bb_middle
  - bb_lower
  - bb_width
  - stochastic_k
  - stochastic_d
  - cmf
  - mfi
  - bar_volatility
  - relative_tick_volume
  - return_1
  - return_3
  - return_5
  - return_10
  - hour
  - weekday
  - session_asian
  - session_london
  - session_ny
  - session_overlap
  max_tp: 28
  min_rr: 2.0
  min_tp: 4
  tp_step: 2
walkforward:
  max_trades_per_week: 120
  min_trades_per_week: 8
  stepback_weeks: 12
  train_window_months: 18
  validation_window_months: 3
  window_weeks: 1
